server:
  port: 8080

spring:
  application:
    name: techl

  datasource:
    platform: mysql
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전